In [6]:
import pandas as pd
df = pd.read_csv(r"C:\Users\aggar\Downloads\customer_shopping_behavior (1).csv")

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [11]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [12]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [13]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [16]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [19]:
labels=['Young Adult','Adult','Middle-Aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [20]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [21]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [22]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [23]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [24]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [32]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [33]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

In [44]:
# CLV Analysis
df['Estimated_CLV'] = (
    df['Purchase Amount (USD)'] *
    df['Previous Purchases']
)

df[['Customer ID','Purchase Amount (USD)',
    'Previous Purchases',
    'Estimated_CLV']].head()

   Customer ID  Purchase Amount (USD)  Previous Purchases  Estimated_CLV
0            1                     53                  14            742
1            2                     64                   2            128
2            3                     73                  23           1679
3            4                     90                  49           4410
4            5                     49                  31           1519

In [45]:
top_clv = df.sort_values(
    'Estimated_CLV',
    ascending=False
)

top_clv.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Estimated_CLV
455,456,54,Male,Blouse,Clothing,100,Utah,XL,Gold,Fall,3.6,Yes,Store Pickup,Yes,Yes,50,Debit Card,Fortnightly,5000
992,993,46,Male,Jacket,Outerwear,99,Louisiana,M,Gray,Winter,4.6,Yes,Express,Yes,Yes,50,Debit Card,Weekly,4950
1847,1848,46,Male,Sandals,Footwear,100,Arizona,XL,Cyan,Summer,4.4,No,Free Shipping,No,No,49,Credit Card,Weekly,4900
1737,1738,42,Male,Jewelry,Accessories,98,Ohio,L,Gray,Summer,4.2,No,Store Pickup,No,No,50,Venmo,Bi-Weekly,4900
3746,3747,53,Female,Coat,Outerwear,99,Idaho,XL,Cyan,Summer,2.6,No,Next Day Air,No,No,49,PayPal,Monthly,4851
2271,2272,29,Male,Dress,Clothing,99,Alaska,M,Green,Summer,3.4,No,Free Shipping,No,No,49,PayPal,Quarterly,4851
885,886,41,Male,Dress,Clothing,99,Ohio,L,Purple,Fall,4.4,Yes,Free Shipping,Yes,Yes,49,Debit Card,Every 3 Months,4851
2229,2230,70,Male,Pants,Clothing,97,Minnesota,M,Silver,Fall,3.9,No,Express,No,No,50,Venmo,Monthly,4850
2484,2485,60,Male,Hoodie,Clothing,97,New Hampshire,M,Green,Summer,4.8,No,2-Day Shipping,No,No,50,Cash,Every 3 Months,4850
2842,2843,28,Female,Coat,Outerwear,100,Arizona,L,Green,Fall,4.3,No,Standard,No,No,48,Debit Card,Quarterly,4800

In [46]:
df.groupby('Subscription Status')['Estimated_CLV'].mean()

Subscription Status
No     1505.324552
Yes    1551.814815
Name: Estimated_CLV, dtype: float64

In [47]:
df['CLV_Segment'] = pd.qcut(
    df['Estimated_CLV'],
    4,
    labels=[
        'Low Value',
        'Medium Value',
        'High Value',
        'VIP'
    ]
)

In [48]:
df['CLV_Segment'].value_counts()

CLV_Segment
Medium Value    977
Low Value       975
VIP             975
High Value      973
Name: count, dtype: int64

In [49]:
df.groupby('CLV_Segment')['Estimated_CLV'].agg(
    ['count','mean','min','max']
).sort_values(
    'mean',
    ascending=False
)

              count         mean   min   max
CLV_Segment
VIP             975  3128.087179  2214  5000
High Value      973  1684.278520  1280  2211
Medium Value    977   941.203685   620  1278
Low Value       975   319.462564    21   616

In [50]:
clv_revenue = df.groupby('CLV_Segment')['Estimated_CLV'].agg(
    ['sum','mean','count']
).sort_values(
    'sum',
    ascending=False
)

clv_revenue

                  sum         mean  count
CLV_Segment
VIP           3049885  3128.087179    975
High Value    1638803  1684.278520    973
Medium Value   919556   941.203685    977
Low Value      311476   319.462564    975

In [51]:
clv_revenue['Revenue_Percentage'] = (
    clv_revenue['sum'] /
    clv_revenue['sum'].sum()
) * 100

clv_revenue

                  sum         mean  count  Revenue_Percentage
CLV_Segment
VIP           3049885  3128.087179    975           51.520764
High Value    1638803  1684.278520    973           27.683792
Medium Value   919556   941.203685    977           15.533775
Low Value      311476   319.462564    975            5.261668

In [52]:
import mysql.connector

In [53]:
import sqlalchemy
import pymysql
print("installed correctly")

installed correctly

In [54]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Apple&2005",
    database="shopping_db"
)

print("Connected successfully")

Connected successfully

In [55]:
username = "root"
password = "Apple&2005"
host = "localhost"
port = "3306"
database = "shopping_db"
from sqlalchemy import create_engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [56]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv(r"C:\Users\aggar\Downloads\customer_shopping_behavior (1).csv")   

engine = create_engine("mysql+mysqlconnector://root:Apple&2005@localhost/shopping_db")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data loaded successfully!")

Data loaded successfully!

In [57]:
df.to_sql(
    "customer_clv",
    engine,
    if_exists="replace",
    index=False
)

3900

In [58]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

In [59]:
df['Estimated_CLV'] = (
    df['Purchase Amount (USD)'] *
    df['Previous Purchases']
)

In [60]:
df[['Customer ID','Purchase Amount (USD)',
    'Previous Purchases',
    'Estimated_CLV']].head()

   Customer ID  Purchase Amount (USD)  Previous Purchases  Estimated_CLV
0            1                     53                  14            742
1            2                     64                   2            128
2            3                     73                  23           1679
3            4                     90                  49           4410
4            5                     49                  31           1519

In [61]:
df['CLV_Segment'] = pd.qcut(
    df['Estimated_CLV'],
    4,
    labels=[
        'Low Value',
        'Medium Value',
        'High Value',
        'VIP'
    ]
)

In [62]:
df['CLV_Segment'].value_counts()

CLV_Segment
Medium Value    977
Low Value       975
VIP             975
High Value      973
Name: count, dtype: int64

In [63]:
df.to_sql(
    "customer_clv",
    engine,
    if_exists="replace",
    index=False
)

3900

In [8]:
churn_df = df.copy()

In [9]:
churn_df['Frequency_Risk'] = churn_df['Previous Purchases'].apply(
    lambda x: 1 if x < churn_df['Previous Purchases'].median() else 0
)

In [10]:
churn_df['Subscription_Risk'] = churn_df['Subscription Status'].apply(
    lambda x: 1 if x == 'No' else 0
)

In [11]:
churn_df['Rating_Risk'] = churn_df['Review Rating'].apply(
    lambda x: 1 if x < 3.5 else 0
)

In [12]:
churn_df['Churn_Risk_Score'] = (
    churn_df['Frequency_Risk'] +
    churn_df['Subscription_Risk'] +
    churn_df['Rating_Risk']
)

In [13]:
def churn_category(score):

    if score >= 2:
        return "High Risk"

    elif score == 1:
        return "Medium Risk"

    else:
        return "Low Risk"


churn_df['Churn_Category'] = churn_df['Churn_Risk_Score'].apply(
    churn_category
)

In [15]:
churn_df['Churn_Category'].value_counts()

Churn_Category
High Risk      2122
Medium Risk    1423
Low Risk        355
Name: count, dtype: int64

In [16]:
churn_df.groupby(
    ['CLV_Segment','Churn_Category']
).size()

KeyError: 'CLV_Segment'

In [74]:
revenue_at_risk = churn_df[
    churn_df['Churn_Category']=="High Risk"
].groupby(
    'CLV_Segment'
)['Estimated_CLV'].sum()

revenue_at_risk

CLV_Segment
Low Value       260249
Medium Value    560735
High Value      703928
VIP             801332
Name: Estimated_CLV, dtype: int64

In [ ]:
churn_df['Priority_Score'] = (
    churn_df['Estimated_CLV'] *
    churn_df['Churn_Risk_Score']
)

churn_df.sort_values(
    'Priority_Score',
    ascending=False
).head(10)

In [76]:
product_perf = df.groupby('Item Purchased').agg({
    'Purchase Amount (USD)': 'sum',
    'Review Rating': 'mean'
}).reset_index()

# thresholds
sales_median = product_perf['Purchase Amount (USD)'].median()
rating_median = product_perf['Review Rating'].median()

def classify(row):
    if row['Purchase Amount (USD)'] >= sales_median and row['Review Rating'] >= rating_median:
        return "Hero Product"
    elif row['Purchase Amount (USD)'] >= sales_median:
        return "Problem Product"
    elif row['Review Rating'] >= rating_median:
        return "Hidden Gem"
    else:
        return "Low Performer"

product_perf['Product_Type'] = product_perf.apply(classify, axis=1)

In [ ]:
df.groupby('Discount Applied')['Purchase Amount (USD)'].agg(['mean','count'])

In [78]:
df.groupby(['Category','Discount Applied'])['Purchase Amount (USD)'].mean()

Category     Discount Applied
Accessories  No                  60.889527
             Yes                 58.489871
Clothing     No                  60.223658
             Yes                 59.752394
Footwear     No                  59.079412
             Yes                 61.799228
Outerwear    No                  58.655556
             Yes                 55.319444
Name: Purchase Amount (USD), dtype: float64

In [ ]:
def persona(row):
    if row['CLV_Segment'] == 'VIP' and row['Subscription Status'] == 'Yes':
        return "VIP Loyalist"
    elif row['Discount Applied'] == 'Yes':
        return "Deal Seeker"
    elif row['Previous Purchases'] < 5:
        return "Occasional Buyer"
    else:
        return "Regular Customer"

df['Persona'] = df.apply(persona, axis=1)

In [80]:
df.groupby(['CLV_Segment','Discount Applied'])['Estimated_CLV'].mean()

CLV_Segment   Discount Applied
Low Value     No                   324.892123
              Yes                  311.352941
Medium Value  No                   946.183521
              Yes                  935.200903
High Value    No                  1675.794063
              Yes                 1694.815668
VIP           No                  3111.137809
              Yes                 3151.542787
Name: Estimated_CLV, dtype: float64

In [81]:
df.groupby(['CLV_Segment','Subscription Status'])['Estimated_CLV'].mean()

CLV_Segment   Subscription Status
Low Value     No                      316.724324
              Yes                     328.085106
Medium Value  No                      941.630000
              Yes                     940.126354
High Value    No                     1679.050360
              Yes                    1697.348921
VIP           No                     3125.283708
              Yes                    3135.676806
Name: Estimated_CLV, dtype: float64

In [17]:
churn_df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases',
 'Frequency_Risk',
 'Subscription_Risk',
 'Rating_Risk',
 'Churn_Risk_Score',
 'Churn_Category']

In [19]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

In [20]:
df['Estimated_CLV'] = (
    df['Purchase Amount (USD)'] *
    df['Previous Purchases']
)

In [21]:
df['CLV_Segment'] = pd.qcut(
    df['Estimated_CLV'],
    4,
    labels=[
        'Low Value',
        'Medium Value',
        'High Value',
        'VIP'
    ]
)

In [22]:
df[['Estimated_CLV','CLV_Segment']].head()

   Estimated_CLV   CLV_Segment
0            742  Medium Value
1            128     Low Value
2           1679    High Value
3           4410           VIP
4           1519    High Value

In [23]:
churn_df = df.copy()

In [24]:
churn_df['Frequency_Risk'] = churn_df['Previous Purchases'].apply(
    lambda x: 1 if x < churn_df['Previous Purchases'].median() else 0
)


churn_df['Subscription_Risk'] = churn_df['Subscription Status'].apply(
    lambda x: 1 if x == 'No' else 0
)


churn_df['Rating_Risk'] = churn_df['Review Rating'].apply(
    lambda x: 1 if x < 3.5 else 0
)

In [25]:
churn_df['Churn_Risk_Score'] = (
    churn_df['Frequency_Risk'] +
    churn_df['Subscription_Risk'] +
    churn_df['Rating_Risk']
)

In [26]:
def churn_category(score):
    if score >= 2:
        return "High Risk"
    elif score == 1:
        return "Medium Risk"
    else:
        return "Low Risk"


churn_df['Churn_Category'] = (
    churn_df['Churn_Risk_Score']
    .apply(churn_category)
)

In [27]:
churn_df.groupby(
    ['CLV_Segment','Churn_Category']
).size()

CLV_Segment   Churn_Category
Low Value     High Risk         824
              Low Risk            4
              Medium Risk       147
Medium Value  High Risk         604
              Low Risk           75
              Medium Risk       298
High Value    High Risk         431
              Low Risk          111
              Medium Risk       431
VIP           High Risk         263
              Low Risk          165
              Medium Risk       547
dtype: int64

In [28]:
churn_df['Retention_Priority'] = (
    churn_df['Estimated_CLV'] *
    churn_df['Churn_Risk_Score']
)

In [29]:
churn_df.sort_values(
    'Retention_Priority',
    ascending=False
).head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Payment Method,Frequency of Purchases,Estimated_CLV,CLV_Segment,Frequency_Risk,Subscription_Risk,Rating_Risk,Churn_Risk_Score,Churn_Category,Retention_Priority
2271,2272,29,Male,Dress,Clothing,99,Alaska,M,Green,Summer,...,PayPal,Quarterly,4851,VIP,0,1,1,2,High Risk,9702
3746,3747,53,Female,Coat,Outerwear,99,Idaho,XL,Cyan,Summer,...,PayPal,Monthly,4851,VIP,0,1,1,2,High Risk,9702
2599,2600,63,Male,Jewelry,Accessories,99,Vermont,M,Gold,Winter,...,Credit Card,Monthly,4752,VIP,0,1,1,2,High Risk,9504
1941,1942,55,Male,Shoes,Footwear,99,Vermont,XL,Peach,Winter,...,Credit Card,Quarterly,4554,VIP,0,1,1,2,High Risk,9108
3435,3436,68,Female,Socks,Clothing,91,Montana,M,Beige,Summer,...,Debit Card,Bi-Weekly,4550,VIP,0,1,1,2,High Risk,9100
1355,1356,59,Male,Shorts,Clothing,91,Florida,M,Blue,Summer,...,PayPal,Bi-Weekly,4550,VIP,0,1,1,2,High Risk,9100
3643,3644,53,Female,Scarf,Accessories,96,Tennessee,XL,Magenta,Fall,...,Debit Card,Annually,4512,VIP,0,1,1,2,High Risk,9024
1840,1841,42,Male,Sandals,Footwear,98,Wyoming,M,Gold,Winter,...,Bank Transfer,Every 3 Months,4508,VIP,0,1,1,2,High Risk,9016
3072,3073,26,Female,Jewelry,Accessories,98,New York,L,Peach,Spring,...,PayPal,Quarterly,4508,VIP,0,1,1,2,High Risk,9016
3393,3394,60,Female,Dress,Clothing,90,Arizona,M,Gold,Fall,...,Debit Card,Monthly,4500,VIP,0,1,1,2,High Risk,9000

In [31]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Apple&2005@localhost/shopping_db"
)

In [32]:
engine.connect()
print("Connected successfully!")

Connected successfully!

In [33]:
churn_df.to_sql(
    "customer_churn_analysis",
    engine,
    if_exists="replace",
    index=False
)

print("Churn table uploaded!")

Churn table uploaded!

In [34]:
product_perf = df.groupby('Item Purchased').agg({
    'Purchase Amount (USD)': 'sum',
    'Review Rating': 'mean'
}).reset_index()

In [35]:
product_perf.head()

  Item Purchased  Purchase Amount (USD)  Review Rating
0       Backpack                   8636       3.752448
1           Belt                   9635       3.763522
2         Blouse                  10410       3.680473
3          Boots                   9018       3.818881
4           Coat                   9275       3.727673

In [36]:
sales_threshold = product_perf['Purchase Amount (USD)'].median()

rating_threshold = product_perf['Review Rating'].median()

print(sales_threshold)
print(rating_threshold)

9275.0
3.75506329113924

In [37]:
def product_category(row):

    if row['Purchase Amount (USD)'] >= sales_threshold and row['Review Rating'] >= rating_threshold:
        return "Hero Product"

    elif row['Purchase Amount (USD)'] < sales_threshold and row['Review Rating'] >= rating_threshold:
        return "Hidden Gem"

    elif row['Purchase Amount (USD)'] >= sales_threshold and row['Review Rating'] < rating_threshold:
        return "Problem Product"

    else:
        return "Low Performer"


product_perf['Product_Segment'] = product_perf.apply(
    product_category,
    axis=1
)

In [38]:
product_perf['Product_Segment'].value_counts()

Product_Segment
Problem Product    8
Hidden Gem         8
Hero Product       5
Low Performer      4
Name: count, dtype: int64

In [39]:
product_perf.sort_values(
    'Purchase Amount (USD)',
    ascending=False
).head(10)

   Item Purchased  Purchase Amount (USD)  Review Rating  Product_Segment
2          Blouse                  10410       3.680473  Problem Product
16          Shirt                  10332       3.622024  Problem Product
5           Dress                  10320       3.750000  Problem Product
13          Pants                  10090       3.720833  Problem Product
12        Jewelry                  10010       3.758824     Hero Product
22     Sunglasses                   9649       3.751572  Problem Product
1            Belt                   9635       3.763522     Hero Product
15          Scarf                   9561       3.705806  Problem Product
23        Sweater                   9462       3.760870     Hero Product
18         Shorts                   9433       3.714194  Problem Product

In [40]:
product_perf.sort_values(
    ['Product_Segment','Purchase Amount (USD)'],
    ascending=[True,False]
)

   Item Purchased  Purchase Amount (USD)  Review Rating  Product_Segment
12        Jewelry                  10010       3.758824     Hero Product
1            Belt                   9635       3.763522     Hero Product
23        Sweater                   9462       3.760870     Hero Product
19          Skirt                   9402       3.785350     Hero Product
8             Hat                   9375       3.801307     Hero Product
21          Socks                   9252       3.755063       Hidden Gem
10         Jacket                   9249       3.763190       Hidden Gem
24        T-shirt                   9248       3.779310       Hidden Gem
14        Sandals                   9200       3.844654       Hidden Gem
3           Boots                   9018       3.818881       Hidden Gem
7         Handbag                   8857       3.775163       Hidden Gem
20       Sneakers                   8635       3.757931       Hidden Gem
6          Gloves                   8477       3.862774       Hidden Gem
17          Shoes                   9240       3.749660    Low Performer
9          Hoodie                   8767       3.716779    Low Performer
0        Backpack                   8636       3.752448    Low Performer
11          Jeans                   7548       3.648387    Low Performer
2          Blouse                  10410       3.680473  Problem Product
16          Shirt                  10332       3.622024  Problem Product
5           Dress                  10320       3.750000  Problem Product
13          Pants                  10090       3.720833  Problem Product
22     Sunglasses                   9649       3.751572  Problem Product
15          Scarf                   9561       3.705806  Problem Product
18         Shorts                   9433       3.714194  Problem Product
4            Coat                   9275       3.727673  Problem Product

In [41]:
product_perf[
    product_perf['Product_Segment']=="Hero Product"
]

   Item Purchased  Purchase Amount (USD)  Review Rating Product_Segment
1            Belt                   9635       3.763522    Hero Product
8             Hat                   9375       3.801307    Hero Product
12        Jewelry                  10010       3.758824    Hero Product
19          Skirt                   9402       3.785350    Hero Product
23        Sweater                   9462       3.760870    Hero Product

In [42]:
product_perf[
    product_perf['Product_Segment']=="Hidden Gem"
]

   Item Purchased  Purchase Amount (USD)  Review Rating Product_Segment
3           Boots                   9018       3.818881      Hidden Gem
6          Gloves                   8477       3.862774      Hidden Gem
7         Handbag                   8857       3.775163      Hidden Gem
10         Jacket                   9249       3.763190      Hidden Gem
14        Sandals                   9200       3.844654      Hidden Gem
20       Sneakers                   8635       3.757931      Hidden Gem
21          Socks                   9252       3.755063      Hidden Gem
24        T-shirt                   9248       3.779310      Hidden Gem

In [43]:
product_perf[
    product_perf['Product_Segment']=="Problem Product"
]

   Item Purchased  Purchase Amount (USD)  Review Rating  Product_Segment
2          Blouse                  10410       3.680473  Problem Product
4            Coat                   9275       3.727673  Problem Product
5           Dress                  10320       3.750000  Problem Product
13          Pants                  10090       3.720833  Problem Product
15          Scarf                   9561       3.705806  Problem Product
16          Shirt                  10332       3.622024  Problem Product
18         Shorts                   9433       3.714194  Problem Product
22     Sunglasses                   9649       3.751572  Problem Product

In [44]:
product_perf[
    product_perf['Product_Segment']=="Low Performer"
]

   Item Purchased  Purchase Amount (USD)  Review Rating Product_Segment
0        Backpack                   8636       3.752448   Low Performer
9          Hoodie                   8767       3.716779   Low Performer
11          Jeans                   7548       3.648387   Low Performer
17          Shoes                   9240       3.749660   Low Performer

In [45]:
product_perf.groupby('Product_Segment').agg({
    'Purchase Amount (USD)': ['sum','mean'],
    'Review Rating':'mean'
})

                Purchase Amount (USD)          Review Rating
                                  sum     mean          mean
Product_Segment
Hero Product                    47884  9576.80      3.773975
Hidden Gem                      71936  8992.00      3.794621
Low Performer                   34191  8547.75      3.716818
Problem Product                 79070  9883.75      3.709072

In [46]:
product_perf.to_sql(
    "product_performance",
    engine,
    if_exists="replace",
    index=False
)

25

In [47]:
persona_df = churn_df.copy()

In [48]:
def assign_persona(row):

    if (
        row['CLV_Segment'] == 'VIP'
        and row['Subscription Status'] == 'Yes'
    ):
        return "VIP Loyalist"

    elif (
        row['Discount Applied'] == 'Yes'
    ):
        return "Deal Seeker"

    elif (
        row['Churn_Category'] == 'High Risk'
    ):
        return "At-Risk Customer"

    else:
        return "Regular Shopper"


persona_df['Customer_Persona'] = persona_df.apply(
    assign_persona,
    axis=1
)

In [49]:
persona_df['Customer_Persona'].value_counts()

Customer_Persona
At-Risk Customer    1494
Deal Seeker         1414
Regular Shopper      729
VIP Loyalist         263
Name: count, dtype: int64

In [50]:
persona_summary = persona_df.groupby(
    'Customer_Persona'
).agg(
    Customers=('Customer ID','count'),
    Avg_CLV=('Estimated_CLV','mean'),
    Avg_Purchase=('Purchase Amount (USD)','mean')
)

persona_summary

                  Customers      Avg_CLV  Avg_Purchase
Customer_Persona
At-Risk Customer       1494  1120.984605     59.447791
Deal Seeker            1414  1227.638614     55.443423
Regular Shopper         729  2310.569273     61.529492
VIP Loyalist            263  3135.676806     79.901141

In [51]:
persona_df['Customer_Persona'].value_counts()

Customer_Persona
At-Risk Customer    1494
Deal Seeker         1414
Regular Shopper      729
VIP Loyalist         263
Name: count, dtype: int64

In [52]:
persona_df.to_sql(
    "customer_personas",
    engine,
    if_exists="replace",
    index=False
)

3900